// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: keygen.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PodInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *PodInfo) Reset() {
	*x = PodInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInfo) ProtoMessage() {}

func (x *PodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInfo.ProtoReflect.Descriptor instead.
func (*PodInfo) Descriptor() ([]byte, []int) {
	return file_keygen_proto_rawDescGZIP(), []int{0}
}

func (x *PodInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PodInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type KeygenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N    int32      `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	M    int32      `protobuf:"varint,2,opt,name=m,proto3" json:"m,omitempty"`
	Pods []*PodInfo `protobuf:"bytes,3,rep,name=pods,proto3" json:"pods,omitempty"`
}

func (x *KeygenRequest) Reset() {
	*x = KeygenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeygenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenRequest) ProtoMessage() {}

func (x *KeygenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenRequest.ProtoReflect.Descriptor instead.
func (*KeygenRequest) Descriptor() ([]byte, []int) {
	return file_keygen_proto_rawDescGZIP(), []int{1}
}

func (x *KeygenRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *KeygenRequest) GetM() int32 {
	if x != nil {
		return x.M
	}
	return 0
}

func (x *KeygenRequest) GetPods() []*PodInfo {
	if x != nil {
		return x.Pods
	}
	return nil
}

type KeygenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Publickey string `protobuf:"bytes,1,opt,name=publickey,proto3" json:"publickey,omitempty"`
}

func (x *KeygenResponse) Reset() {
	*x = KeygenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeygenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenResponse) ProtoMessage() {}

func (x *KeygenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenResponse.ProtoReflect.Descriptor instead.
func (*KeygenResponse) Descriptor() ([]byte, []int) {
	return file_keygen_proto_rawDescGZIP(), []int{2}
}

func (x *KeygenResponse) GetPublickey() string {
	if x != nil {
		return x.Publickey
	}
	return ""
}

type KeygenFinishedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Publickey string `protobuf:"bytes,1,opt,name=publickey,proto3" json:"publickey,omitempty"`
}

func (x *KeygenFinishedRequest) Reset() {
	*x = KeygenFinishedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeygenFinishedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenFinishedRequest) ProtoMessage() {}

func (x *KeygenFinishedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenFinishedRequest.ProtoReflect.Descriptor instead.
func (*KeygenFinishedRequest) Descriptor() ([]byte, []int) {
	return file_keygen_proto_rawDescGZIP(), []int{3}
}

func (x *KeygenFinishedRequest) GetPublickey() string {
	if x != nil {
		return x.Publickey
	}
	return ""
}

type KeygenFinishedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *KeygenFinishedResponse) Reset() {
	*x = KeygenFinishedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keygen_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeygenFinishedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenFinishedResponse) ProtoMessage() {}

func (x *KeygenFinishedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keygen_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenFinishedResponse.ProtoReflect.Descriptor instead.
func (*KeygenFinishedResponse) Descriptor() ([]byte, []int) {
	return file_keygen_proto_rawDescGZIP(), []int{4}
}

func (x *KeygenFinishedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_keygen_proto protoreflect.FileDescriptor

var file_keygen_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x22, 0x2d, 0x0a, 0x07, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x50, 0x0a, 0x0d, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x01, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x6d, 0x12, 0x23, 0x0a, 0x04, 0x70, 0x6f, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x70, 0x6f, 0x64, 0x73, 0x22, 0x2e, 0x0a, 0x0e, 0x4b, 0x65, 0x79, 0x67, 0x65,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x79, 0x22, 0x35, 0x0a, 0x15, 0x4b, 0x65, 0x79, 0x67, 0x65,
	0x6e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x79, 0x22, 0x32,
	0x0a, 0x16, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0xa0, 0x01, 0x0a, 0x0d, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x4b, 0x65, 0x79, 0x12, 0x15, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x4b, 0x65, 0x79,
	0x67, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6b, 0x65, 0x79,
	0x67, 0x65, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x51, 0x0a, 0x0e, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x65, 0x64, 0x12, 0x1d, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x4b, 0x65,
	0x79, 0x67, 0x65, 0x6e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x2e, 0x4b, 0x65, 0x79,
	0x67, 0x65, 0x6e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x22, 0x5a, 0x20, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x79, 0x61, 0x70, 0x70, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_keygen_proto_rawDescOnce sync.Once
	file_keygen_proto_rawDescData = file_keygen_proto_rawDesc
)

func file_keygen_proto_rawDescGZIP() []byte {
	file_keygen_proto_rawDescOnce.Do(func() {
		file_keygen_proto_rawDescData = protoimpl.X.CompressGZIP(file_keygen_proto_rawDescData)
	})
	return file_keygen_proto_rawDescData
}

var file_keygen_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_keygen_proto_goTypes = []any{
	(*PodInfo)(nil),                // 0: keygen.PodInfo
	(*KeygenRequest)(nil),          // 1: keygen.KeygenRequest
	(*KeygenResponse)(nil),         // 2: keygen.KeygenResponse
	(*KeygenFinishedRequest)(nil),  // 3: keygen.KeygenFinishedRequest
	(*KeygenFinishedResponse)(nil), // 4: keygen.KeygenFinishedResponse
}
var file_keygen_proto_depIdxs = []int32{
	0, // 0: keygen.KeygenRequest.pods:type_name -> keygen.PodInfo
	1, // 1: keygen.KeygenService.GenerateKey:input_type -> keygen.KeygenRequest
	3, // 2: keygen.KeygenService.KeygenFinished:input_type -> keygen.KeygenFinishedRequest
	2, // 3: keygen.KeygenService.GenerateKey:output_type -> keygen.KeygenResponse
	4, // 4: keygen.KeygenService.KeygenFinished:output_type -> keygen.KeygenFinishedResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_keygen_proto_init() }
func file_keygen_proto_init() {
	if File_keygen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_keygen_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PodInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*KeygenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*KeygenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*KeygenFinishedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keygen_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*KeygenFinishedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keygen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keygen_proto_goTypes,
		DependencyIndexes: file_keygen_proto_depIdxs,
		MessageInfos:      file_keygen_proto_msgTypes,
	}.Build()
	File_keygen_proto = out.File
	file_keygen_proto_rawDesc = nil
	file_keygen_proto_goTypes = nil
	file_keygen_proto_depIdxs = nil
}
