apiVersion: apps/v1
kind: Deployment
metadata:
  name: tss-gateway
  labels:
    app: tss-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tss-gateway
  template:
    metadata:
      labels:
        app: tss-gateway
    spec:
      containers:
      - name: tss-gateway
        image: tss-gateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
