apiVersion: apps/v1
kind: Deployment
metadata:
  name: tss-party
  labels:
    app: tss-party
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tss-party
  template:
    metadata:
      labels:
        app: tss-party
    spec:
      containers:
      - name: tss-party
        image: tss-party:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9090
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 15
          periodSeconds: 20
